server:
  port: 9094

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/
    register-with-eureka: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoiceDB?useTimezone=true&serverTimezone=UTC&autoreconnect=true&createDatabaseIfNotExist=TRUE
    username: root
    password: legalizzr
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9191/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin

api:
  path:
    customer:
      host: http://localhost:9093
      basePath: /v1
      customers: /customers